name       : Install Dependencies
description: 'Install Dependencies'

runs:
    using: 'composite'
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6      # todo: refactor code to support 3.11
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-pip-
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .