name: Run Python Tests
description: 'Run Python Tests'

inputs:
  codecov_token:
    description: 'CodeCov access token'
    required: true
  package_name:
    description: 'Package name for coverage'
    required: true
  open_api__api_key:
    description: 'OpenAI API_KEY'
    required: true
  aws_access_key_id:
    description: 'AWS Account KEY ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_default_region:
    description: 'AWS Default region'
    required: true
  aws_account_id:
    description: 'AWS Account ID'
    required: true

runs:
    using: 'composite'
    steps:
      - name: Run tests with pytest (with coverage)
        shell: bash
        run: |
          coverage run --source=${{ inputs.package_name }} -m pytest -v -s --durations=0 --ignore=tests_* tests
        env:
          OPEN_AI__API_KEY     : ${{ inputs.open_api__api_key     }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
          AWS_DEFAULT_REGION   : ${{ inputs.aws_default_region    }}
          AWS_ACCOUNT_ID       : ${{ inputs.aws_account_id        }}
          AWS_ACCESS_KEY_ID    : ${{ inputs.aws_access_key_id     }}
      - name: Print coverage report
        shell: bash
        run: |
          coverage report -m
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v3
#        env:
#          CODECOV_TOKEN         : ${{ inputs.codecov_token         }}
#          OPEN_AI__API_KEY      : ${{ inputs.open_api__api_key     }}