name       : Run Unit Tests
on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Unit Tests
        uses: ./.github/actions/run-unit-tests
        with:
          codecov_token         : ${{ secrets.CODECOV_TOKEN         }}
          package_name          : ${{ secrets.PACKAGE_NAME          }}
          open_api__api_key     : ${{ secrets.OPEN_AI__API_KEY      }}
          aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region    : ${{ secrets.AWS_DEFAULT_REGION    }}
          aws_account_id        : ${{ secrets.AWS_ACCOUNT_ID        }}
          aws_access_key_id     : ${{ secrets.AWS_ACCESS_KEY_ID     }}